name: Scan Unavailable Manifest
on:
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Setup
        run: |
         cd ../
         git clone https://github.com/microsoft/winget-pkgs
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Env
        run: python3 -m pip install -r requirements.txt
      - name: Scan
        run: python3 src/scan.py ${{ secrets.TOKEN }}
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with:
          timeZone: 8
          format: "YYYYMMDDHHmmss"
      - name: Commit
        id: commit
        run:
         cd winget-pkgs
         if [[ -n $(git status -s) ]]; then
         git config --global user.email coolplaylin@qq.com
         git config --global user.name CoolPlayLin
         git remote set-url own https://github.com/CoolPlayLin/winget-pkgs.git
         git checkout -b patch-${{ steps.time.outputs.time }}
         git add .
         git commit -m "Delete Unavailable Manifests"
         echo "status=Changed" >> "$GITHUB_OUTPUT"
         git push --set-upstream own patch-${{ steps.time.outputs.time }}
         fi
      - name: Open PR
        run: echo "Pass"
